name: The Direct Sales Party Girl
favicon: null
layout_spectrum: 0.9013287825509906
typography_spectrum: 0.07319206884130836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7041590420994908
  lightness: 0.7966613660100847
  saturation: 0.7232348609250039
  rhythmicContrast: 0.8906453701201826
purpose: []
